---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp1
    image: nginx:1.14.2
    ports:
      - containerPort: 8080
  - name: myapp2
    image: nginx:1.14.2
    ports:
      - containerPort: 8081
    command:
      - sleep
      - "30"