apiVersion: v1
kind: Pod
metadata:
  name: web-nginx-edited
  labels:
    app : nginx
spec:
  containers:
    - name: web-edited
      image: nginx
      ports:
        - containerPort: 80
          name: web
          protocol: TCP