---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-apps
  namespace: shadi-namespace
spec:
  replicas: 4
  selector:
    matchLabels:
      tag: nginx-app
  template:
    metadata:
      labels:
        tag: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
