apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: NodePort
  externalIPs:
    - 125.100.99.101
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50000
      name: http
  selector:
    app: nginx