apiVersion: v1
kind: Pod
metadata:
  name: good-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
    resources:
      requests:
        memory: "50M"
        cpu: "250m"